### ISSUE TITLE
/quote *text* gives quote containing *text*

### ISSUE THREAD

**Issue by PowerToTheUsers** [slimmii/trogdor#5]
een soort van zoekfunctie dus. IRC-style :)

**Comment by kwyckmans** [comment]
+1

**Comment by rubenvereecken** [comment]
Is logdor hier hiervoor nodig @slimmii ?

**Comment by slimmii** [comment]
Nee, da's de irc !quote alternatief... Der is een tabelleke voor in onze postgres. Als ge hier aan wilt werken kannek u de credentials wel geven.

**Comment by Licargon** [comment]
Ik heb hier (99% zeker, kant lokaal ni perfect testen :/ ) werkende code voor. Will add once I get access :)

**Comment by Licargon** [comment]
Done
